=== ale-val/web-system-architecture-springboot/src/main/resources/static/xml/listaPostSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

    <xs:element name="posts">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="post" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="utente" type="xs:string"/>
                            <xs:element name="timestamp" type="xs:dateTime"/>
                            <xs:element name="contenuto">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:maxLength value="280"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>

                            <xs:element name="commenti" minOccurs="0">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="commento" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="utente" type="xs:string"/>
                                                    <xs:element name="timestamp" type="xs:dateTime"/>
                                                    <xs:element name="commentText">
                                                        <xs:simpleType>
                                                            <xs:restriction base="xs:string">
                                                                <xs:maxLength value="120"/>
                                                            </xs:restriction>
                                                        </xs:simpleType>
                                                    </xs:element>
                                                </xs:sequence>
                                                <xs:attribute name="id" type="xs:int" use="required"/>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="id" type="xs:int" use="required"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== ale-val/web-system-architecture-springboot/src/main/resources/static/xml/listaPost1.xml
<?xml version="1.0" encoding="UTF-8"?>
<posts xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:noNamespaceSchemaLocation="listaPostSchema.xsd">
    <post id="1">
        <utente>Alessandro</utente>
        <timestamp>2024-11-09T10:30:00</timestamp>
        <contenuto>Guarda cosa ho fatto oggi :)</contenuto>
        <commenti>
            <commento id="1">
                <utente>utente1</utente>
                <timestamp>2024-11-09T11:00:00</timestamp>
                <commentText>Assurdo</commentText>
            </commento>
            <commento id="2">
                <utente>utente2</utente>
                <timestamp>2024-11-09T11:15:00</timestamp>
                <commentText>bellissimo</commentText>
            </commento>
        </commenti>
    </post>
    <post id="2">
        <utente>Alfonso</utente>
        <timestamp>2024-11-08T18:45:00</timestamp>
        <contenuto>Come state?</contenuto>
    </post>
    <post id="3">
        <utente>Franco</utente>
        <timestamp>2024-11-12T10:30:00</timestamp>
        <contenuto>Il mio nuovo telefono!!</contenuto>
        <commenti>
            <commento id="1">
                <utente>utente1</utente>
                <timestamp>2024-11-09T11:00:00</timestamp>
                <commentText>Assurdo</commentText>
            </commento>
            <commento id="2">
                <utente>utente2</utente>
                <timestamp>2024-11-09T11:15:00</timestamp>
                <commentText>bellissimo</commentText>
            </commento>
            <commento id="3">
                <utente>utente2</utente>
                <timestamp>2024-11-09T11:15:00</timestamp>
                <commentText>bellissimo</commentText>
            </commento>
        </commenti>
    </post>
    <post id="4">
        <utente>Alfonso</utente>
        <timestamp>2024-11-08T18:45:00</timestamp>
        <contenuto>Cosa facciamo questa sera?</contenuto>
    </post>
</posts>

=== ale-val/web-system-architecture-springboot/src/main/resources/static/xml/listaPost2.xml
<?xml version="1.0" encoding="UTF-8"?>
<posts xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:noNamespaceSchemaLocation="listaPostSchema.xsd">
    <post id="3">
        <utente>Giovanni</utente>
        <timestamp>2024-11-09T19:30:00</timestamp>
        <contenuto>Buongiorno!!</contenuto>
        <commenti>
            <commento id="1">
                <utente>utente1</utente>
                <timestamp>2024-11-09T11:00:00</timestamp>
                <commentText>Anche a te</commentText>
            </commento>
        </commenti>
    </post>
    <post id="4">
        <utente>Silvestro</utente>
        <timestamp>2024-11-08T21:32:00</timestamp>
        <contenuto>La mia nuova macchina!</contenuto>
        <commenti>
            <commento id="1">
                <utente>utente3</utente>
                <timestamp>2024-11-09T11:00:00</timestamp>
                <commentText>Stupenda</commentText>
            </commento>
        </commenti>
    </post>
</posts>
